// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.Close")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.WriteCSV(System.String,System.String,System.String,System.Nullable{System.Int32},System.Nullable{System.Boolean})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.BenchmarkIterationStop(System.String,System.String,System.Int32,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkTestCase.#ctor(Xunit.Abstractions.IMessageSink,Xunit.Sdk.TestMethodDisplay,Xunit.Abstractions.ITestMethod,Xunit.Abstractions.IAttributeInfo,System.Object[])")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0133:Parameter name differs in base declaration", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkDiscoverer.Discover(Xunit.Abstractions.ITestFrameworkDiscoveryOptions,Xunit.Abstractions.ITestMethod,Xunit.Abstractions.IAttributeInfo)~System.Collections.Generic.IEnumerable{Xunit.Sdk.IXunitTestCase}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S927:parameter names should match base declaration and other partial definitions", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkDiscoverer.Discover(Xunit.Abstractions.ITestFrameworkDiscoveryOptions,Xunit.Abstractions.ITestMethod,Xunit.Abstractions.IAttributeInfo)~System.Collections.Generic.IEnumerable{Xunit.Sdk.IXunitTestCase}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S1215:\"GC.Collect\" should not be called", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkTestInvoker.BenchmarkIteratorImpl.GetIterations~System.Collections.Generic.IEnumerable{Microsoft.Xunit.Performance.BenchmarkIteration}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Critical Code Smell", "S1215:\"GC.Collect\" should not be called", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Execution.AllocatedBytesForCurrentThread.IsBugFixed~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1034:Nested types should not be visible", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.Xunit.Performance.BenchmarkEventSource.Tasks")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkTestCaseRunner.AfterTestCaseStartingAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.BenchmarkIterationStart(System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.BenchmarkIterationStop(System.String,System.String,System.Int32,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.BenchmarkStart(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.BenchmarkStop(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.Clear")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.Close")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.Flush")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.GetTimestamp~System.Double")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Execution.AllocatedBytesForCurrentThread.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkEventSource.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Execution.AllocatedBytesForCurrentThread.#cctor")]