// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3928:Parameter names used into ArgumentException constructors should match an existing one ", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Api.Table.CSVReader.GetValue(System.Int32,System.Int32)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3928:Parameter names used into ArgumentException constructors should match an existing one ", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Api.Table.CSVReader.GetValue(System.Int32,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3928:Parameter names used into ArgumentException constructors should match an existing one ", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Api.Table.CSVReader.LineLength(System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3928:Parameter names used into ArgumentException constructors should match an existing one ", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.Xunit.Performance.Api.ScenarioTestConfiguration.SuccessExitCodes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1172:Unused method parameters should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Api.AssemblyModel.GetCollectedData(System.String,Microsoft.Xunit.Performance.Api.CSVMetricReader,Microsoft.Xunit.Performance.Api.XUnitPerformanceMetricData)~System.Collections.Generic.IEnumerable{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0034:Simplify 'default' expression", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Api.DictionaryExtensions.GetOrDefault``2(System.Collections.Generic.IDictionary{``0,``1},``0,``1)~``1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Api.AssemblyModel.GetCollectedData(System.String,Microsoft.Xunit.Performance.Api.CSVMetricReader,Microsoft.Xunit.Performance.Api.XUnitPerformanceMetricData)~System.Collections.Generic.IEnumerable{System.}")]