// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3442:\"abstract\" classes should not have \"public\" constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.ProviderInfo.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3442:\"abstract\" classes should not have \"public\" constructors", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Sdk.PerformanceMetric.#ctor(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.Xunit.Performance.InstructionsRetiredMetricDiscoverer.InstructionsRetiredMetric")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Info Code Smell", "S1135:Track uses of \"TODO\" tags", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.Xunit.Performance.InstructionsRetiredMetricDiscoverer.InstructionsRetiredMetric")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2235:Mark all non-serializable fields", Justification = "<Pending>", Scope = "member", Target = "~P:Microsoft.Xunit.Performance.UserProviderInfo.ProviderGuid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.BenchmarkMetricDiscoverer.BenchmarkDurationEvaluator.#ctor(Microsoft.Xunit.Performance.Sdk.PerformanceMetricEvaluationContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1134:Track uses of \"FIXME\" tags", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.InstructionsRetiredMetricDiscoverer.InstructionsRetiredEvaluator.Initialize(Microsoft.Xunit.Performance.Sdk.PerformanceMetricEvaluationContext,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0007:Use implicit type", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Xunit.Performance.Sdk.PerformanceMetric.GetProfileSourceInfoId(System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkIterationStartArgs.#ctor(System.Action{Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkIterationStartArgs},System.Int32,System.Int32,System.String,System.Guid,System.Int32,System.String,System.Guid,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkIterationStopArgs.#ctor(System.Action{Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkIterationStopArgs},System.Int32,System.Int32,System.String,System.Guid,System.Int32,System.String,System.Guid,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkStartArgs.#ctor(System.Action{Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkStartArgs},System.Int32,System.Int32,System.String,System.Guid,System.Int32,System.String,System.Guid,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkStopArgs.#ctor(System.Action{Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkStopArgs},System.Int32,System.Int32,System.String,System.Guid,System.Int32,System.String,System.Guid,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.EventSourceMessageArgs.#ctor(System.Action{Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.EventSourceMessageArgs},System.Int32,System.Int32,System.String,System.Guid,System.Int32,System.String,System.Guid,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkIterationStartArgs.m_target")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkIterationStopArgs.m_target")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkStartArgs.m_target")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.BenchmarkStopArgs.m_target")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~E:Microsoft.Diagnostics.Tracing.Parsers.MicrosoftXunitBenchmark.EventSourceMessageArgs.m_target")]